/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Domain.Bodega;
import Domain.Categoria;
import Domain.ProductoMayorista;
import Logica.GraphAdyacency;
import Logica.GraphException;
import Logica.LinkedBinaryTree;
import Logica.TreeExceptions;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melvin
 */
public class DeleteUpdateBodega extends javax.swing.JFrame {

    /**
     * Creates new form deleteUpdateBodega
     */
    public DeleteUpdateBodega() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("C:\\Users\\Melvin\\Desktop\\RepositorioProyecto2Algoritmos\\src\\Imagenes\\Logo.PNG");
        Icon icon2 = new ImageIcon(icon.getImage().getScaledInstance(lbl_ICON.getWidth(), lbl_ICON.getHeight(), Image.SCALE_DEFAULT));
        lbl_ICON.setIcon(icon2);
        this.repaint();
        
        
        
         DefaultTableModel model = (DefaultTableModel) this.table_Bodega.getModel();
        model.setRowCount(0);
        Object O[] = null;
        
             LinkedList<Bodega> listBodega = LoginPanel.bodega.recorreGraph();
        cargarTablaBodegas(table_Bodega, listBodega);
        tfd_IDBodegaAEliminar.setEnabled(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Bodega = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lbl_ICON = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfd_IDBodegaAEliminar = new javax.swing.JTextField();
        lbl_Mensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Delete or Update Bodega");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 32, -1, -1));

        table_Bodega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Latitud", "Longitud", "Distancia", "Fotografia"
            }
        ));
        table_Bodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_BodegaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Bodega);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 89, 875, 435));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 12, 143, 59));

        lbl_ICON.setText("jLabel2");
        getContentPane().add(lbl_ICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 604, 130, 120));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 670, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("La ID de la bodega a eliminar es:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 310, -1));

        tfd_IDBodegaAEliminar.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        getContentPane().add(tfd_IDBodegaAEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, 200, 30));

        lbl_Mensaje.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_Mensaje.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(lbl_Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 390, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public void cargarTablaBodegas(JTable producto, LinkedList<Bodega> list) {
        DefaultTableModel model = (DefaultTableModel) producto.getModel();
        model.setRowCount(0);
        Object O[] = null;
        for (int i = 0; i < list.size(); i++) {
  
            model.addRow(O);
            Bodega bodega = (Bodega) list.get(i);
          Bodega bodega1 = (Bodega) list.get(i);
            model.setValueAt(bodega1.getId(), i, 0);
            model.setValueAt(bodega1.getNombre(), i, 1);
            model.setValueAt(bodega1.getLatitud(), i, 2);
            model.setValueAt(bodega1.getLongitud(), i, 3);
             model.setValueAt(bodega1.getDistanciaCentroOperaciones(), i, 4);
            model.setValueAt(bodega1.getUrlFoto(), i, 5);

        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdministratorPanel administradorPanel = new AdministratorPanel();
        this.dispose();
        administradorPanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_BodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_BodegaMouseClicked
        // TODO add your handling code here:
        this.lbl_Mensaje.setText("");
        int row = this.table_Bodega.getSelectedRow();
        int id = Integer.parseInt(this.table_Bodega.getValueAt(row, 0).toString());
        tfd_IDBodegaAEliminar.setText(id+"");
        
    }//GEN-LAST:event_table_BodegaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            LinkedList<Bodega> listaBodegas = LoginPanel.bodega.recorreGraph();
        
         String idBuscada = tfd_IDBodegaAEliminar.getText();
        String miID = "no lo borraste";
        for (int i = 0; i < listaBodegas.size(); i++) {
  
            Bodega bodega = (Bodega) listaBodegas.get(i);
            if(bodega.getId()== Integer.parseInt(idBuscada)){
                listaBodegas.remove(bodega);
                miID = "LO BORRASTE";
                tfd_IDBodegaAEliminar.setText("");
                lbl_Mensaje.setText("La bodega ha sido eliminado con exito");
                break;
            }
            
         }
        
        GraphAdyacency grafoNuevo = new GraphAdyacency(100);
       // LinkedBinaryTree arbolNuevo = new LinkedBinaryTree();
        for (int i = 0; i < listaBodegas.size(); i++) {
            try {
                Bodega bodega = (Bodega) listaBodegas.get(i);
                grafoNuevo.insertVertex(bodega);
            }   catch (GraphException ex) {
                    Logger.getLogger(DeleteUpdateBodega.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        LoginPanel.bodega = grafoNuevo;
        
        System.out.println(miID);
         cargarTablaBodegas(table_Bodega, listaBodegas);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUpdateBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUpdateBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUpdateBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUpdateBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUpdateBodega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ICON;
    private javax.swing.JLabel lbl_Mensaje;
    private javax.swing.JTable table_Bodega;
    private javax.swing.JTextField tfd_IDBodegaAEliminar;
    // End of variables declaration//GEN-END:variables
}
