/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Domain.Bodega;
import Logica.GraphException;
import java.awt.Image;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Melvin
 */
public class InsertBodega extends javax.swing.JFrame {

    int id;
    
    /**
     * Creates new form insertBodega
     */
    public InsertBodega() throws GraphException {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("C:\\Users\\Melvin\\Desktop\\RepositorioProyecto2Algoritmos\\src\\Imagenes\\Logo.PNG");
        Icon icon2 = new ImageIcon(icon.getImage().getScaledInstance(lbl_LOGO.getWidth(), lbl_LOGO.getHeight(), Image.SCALE_DEFAULT));
        lbl_LOGO.setIcon(icon2);
        this.repaint();
        
        if(LoginPanel.bodega.isEmpty()){
        lbl_ID2.setText("1");
        }else{
           // Iterator it = LoginPanel.bodega.keySet().iterator();
            //while(it.hasNext()){
              //  Integer key = (Integer)it.next();
               // id = LoginPanel.bodega.get(key).getId()+1;
               
            }
           // lbl_ID2.setText(id+"");
        //
       tfd_Foto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_InsertBodega = new javax.swing.JLabel();
        lbl_ID1 = new javax.swing.JLabel();
        lbl_ID2 = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        tfd_Nombre = new javax.swing.JTextField();
        lbl_Latitud = new javax.swing.JLabel();
        tfd_Latitud = new javax.swing.JTextField();
        lbl_Longitud = new javax.swing.JLabel();
        tfd_Longitud = new javax.swing.JTextField();
        lbl_Distancia = new javax.swing.JLabel();
        tfd_Distancia = new javax.swing.JTextField();
        lbl_Fotografia = new javax.swing.JLabel();
        btn_BuscarFoto = new javax.swing.JButton();
        tfd_Foto = new javax.swing.JTextField();
        lbl_Foto = new javax.swing.JLabel();
        btn_InsertBodega = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_LOGO = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_InsertBodega.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        lbl_InsertBodega.setForeground(new java.awt.Color(255, 255, 0));
        lbl_InsertBodega.setText("Insert Bodega");
        getContentPane().add(lbl_InsertBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 22, -1, -1));

        lbl_ID1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_ID1.setForeground(new java.awt.Color(255, 255, 0));
        lbl_ID1.setText("ID");
        getContentPane().add(lbl_ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 117, -1, -1));

        lbl_ID2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_ID2.setForeground(new java.awt.Color(255, 255, 0));
        lbl_ID2.setText("jLabel3");
        getContentPane().add(lbl_ID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 117, -1, -1));

        lbl_Nombre.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Nombre.setText("Nombre");
        getContentPane().add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 196, -1, -1));

        tfd_Nombre.setBackground(new java.awt.Color(0, 0, 0));
        tfd_Nombre.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        tfd_Nombre.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(tfd_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 196, 171, -1));

        lbl_Latitud.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_Latitud.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Latitud.setText("Latitud");
        getContentPane().add(lbl_Latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 268, -1, -1));

        tfd_Latitud.setBackground(new java.awt.Color(0, 0, 0));
        tfd_Latitud.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        tfd_Latitud.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(tfd_Latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 273, 171, -1));

        lbl_Longitud.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_Longitud.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Longitud.setText("Longitud");
        getContentPane().add(lbl_Longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 353, -1, -1));

        tfd_Longitud.setBackground(new java.awt.Color(0, 0, 0));
        tfd_Longitud.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        tfd_Longitud.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(tfd_Longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 353, 171, -1));

        lbl_Distancia.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_Distancia.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Distancia.setText("Distancia Centro Operaciones");
        getContentPane().add(lbl_Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 408, -1, -1));

        tfd_Distancia.setBackground(new java.awt.Color(0, 0, 0));
        tfd_Distancia.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        tfd_Distancia.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(tfd_Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 310, -1));

        lbl_Fotografia.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_Fotografia.setForeground(new java.awt.Color(255, 255, 0));
        lbl_Fotografia.setText("Fotografia");
        getContentPane().add(lbl_Fotografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 506, -1, -1));

        btn_BuscarFoto.setBackground(new java.awt.Color(0, 0, 0));
        btn_BuscarFoto.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btn_BuscarFoto.setForeground(new java.awt.Color(255, 255, 0));
        btn_BuscarFoto.setText("Buscar Fotografia");
        getContentPane().add(btn_BuscarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 501, -1, -1));

        tfd_Foto.setBackground(new java.awt.Color(0, 0, 0));
        tfd_Foto.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        tfd_Foto.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(tfd_Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 553, 317, 30));

        lbl_Foto.setText("jLabel9");
        getContentPane().add(lbl_Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 609, 160, 98));

        btn_InsertBodega.setBackground(new java.awt.Color(0, 0, 0));
        btn_InsertBodega.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btn_InsertBodega.setForeground(new java.awt.Color(255, 255, 0));
        btn_InsertBodega.setText("Insert Bodega");
        btn_InsertBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertBodegaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_InsertBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 234, 38));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, 220, 50));

        lbl_LOGO.setText("jLabel1");
        getContentPane().add(lbl_LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 730, 120, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertBodegaActionPerformed
        // TODO add your handling code here:
        if(tfd_Distancia.getText().equals("")||tfd_Foto.getText().equals("")||tfd_Latitud.getText().equals("")||tfd_Longitud.getText().equals("")||tfd_Nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete todos los espacios por favor");
        }else{
            
            Bodega bodega  = new Bodega(Integer.parseInt(lbl_ID2.getText()), tfd_Nombre.getText(), tfd_Latitud.getText(), tfd_Longitud.getText(), Float.parseFloat(tfd_Distancia.getText())  , tfd_Foto.getText());
            try {
                LoginPanel.bodega.insertVertex(bodega);
            } catch (GraphException ex) {
                Logger.getLogger(InsertBodega.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_btn_InsertBodegaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdministratorPanel administradorPanel = new AdministratorPanel();
        this.dispose();
        administradorPanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsertBodega().setVisible(true);
                } catch (GraphException ex) {
                    Logger.getLogger(InsertBodega.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarFoto;
    private javax.swing.JButton btn_InsertBodega;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lbl_Distancia;
    private javax.swing.JLabel lbl_Foto;
    private javax.swing.JLabel lbl_Fotografia;
    private javax.swing.JLabel lbl_ID1;
    private javax.swing.JLabel lbl_ID2;
    private javax.swing.JLabel lbl_InsertBodega;
    private javax.swing.JLabel lbl_LOGO;
    private javax.swing.JLabel lbl_Latitud;
    private javax.swing.JLabel lbl_Longitud;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JTextField tfd_Distancia;
    private javax.swing.JTextField tfd_Foto;
    private javax.swing.JTextField tfd_Latitud;
    private javax.swing.JTextField tfd_Longitud;
    private javax.swing.JTextField tfd_Nombre;
    // End of variables declaration//GEN-END:variables
}
