/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Melvin
 */
public class insertProductoMayorista extends javax.swing.JFrame {

    /**
     * Creates new form insertProductoMayorista
     */
    public insertProductoMayorista() {
        initComponents();
        tfd_URLFoto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_InsertProduct = new javax.swing.JLabel();
        lbl_ID1 = new javax.swing.JLabel();
        lbl_ID2 = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        tfd_Nombre = new javax.swing.JTextField();
        lbl_UnidadMedida = new javax.swing.JLabel();
        tfd_UnidadMedida = new javax.swing.JTextField();
        lbl_ValorUnidad = new javax.swing.JLabel();
        tfd_ValorUnidad = new javax.swing.JTextField();
        lbl_PesoTotal = new javax.swing.JLabel();
        tfd_PesoTotal = new javax.swing.JTextField();
        lbl_Descripcion = new javax.swing.JLabel();
        tfd_Descripcion = new javax.swing.JTextField();
        lbl_IDLote = new javax.swing.JLabel();
        tfd_IDLote = new javax.swing.JTextField();
        lbl_IDCategoria = new javax.swing.JLabel();
        tfd_IDCategoria = new javax.swing.JTextField();
        lbl_PrecioTotal = new javax.swing.JLabel();
        tfd_precioTotal = new javax.swing.JTextField();
        lbl_Fotografia = new javax.swing.JLabel();
        lbl_FOTO = new javax.swing.JLabel();
        btn_BuscarFoto = new javax.swing.JButton();
        tfd_URLFoto = new javax.swing.JTextField();
        btn_InsertOProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_InsertProduct.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        lbl_InsertProduct.setForeground(new java.awt.Color(0, 102, 102));
        lbl_InsertProduct.setText("Insert Producto Mayorista");
        getContentPane().add(lbl_InsertProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 465, 51));

        lbl_ID1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_ID1.setForeground(new java.awt.Color(0, 102, 102));
        lbl_ID1.setText("ID");
        getContentPane().add(lbl_ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 69, 45, 39));

        lbl_ID2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_ID2.setForeground(new java.awt.Color(0, 102, 102));
        lbl_ID2.setText("jLabel3");
        getContentPane().add(lbl_ID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 69, 73, 39));

        lbl_Nombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(0, 102, 102));
        lbl_Nombre.setText("Nombre");
        getContentPane().add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 126, 100, 36));
        getContentPane().add(tfd_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 137, 255, -1));

        lbl_UnidadMedida.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_UnidadMedida.setForeground(new java.awt.Color(0, 102, 102));
        lbl_UnidadMedida.setText("Unidad de Medida");
        getContentPane().add(lbl_UnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 189, -1, -1));
        getContentPane().add(tfd_UnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 194, 255, -1));

        lbl_ValorUnidad.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_ValorUnidad.setForeground(new java.awt.Color(0, 102, 102));
        lbl_ValorUnidad.setText("Valor de Unidad");
        getContentPane().add(lbl_ValorUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 247, -1, -1));
        getContentPane().add(tfd_ValorUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 252, 255, -1));

        lbl_PesoTotal.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_PesoTotal.setForeground(new java.awt.Color(0, 102, 102));
        lbl_PesoTotal.setText("Peso Total");
        getContentPane().add(lbl_PesoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 312, 137, -1));
        getContentPane().add(tfd_PesoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 317, 255, -1));

        lbl_Descripcion.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_Descripcion.setForeground(new java.awt.Color(0, 102, 102));
        lbl_Descripcion.setText("Descripcion");
        getContentPane().add(lbl_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 377, -1, -1));
        getContentPane().add(tfd_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 382, 255, -1));

        lbl_IDLote.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_IDLote.setForeground(new java.awt.Color(0, 102, 102));
        lbl_IDLote.setText("ID Lote");
        getContentPane().add(lbl_IDLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 459, -1, -1));
        getContentPane().add(tfd_IDLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 464, 255, -1));

        lbl_IDCategoria.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_IDCategoria.setForeground(new java.awt.Color(0, 102, 102));
        lbl_IDCategoria.setText("ID Categoria");
        getContentPane().add(lbl_IDCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 528, -1, -1));
        getContentPane().add(tfd_IDCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 533, 255, -1));

        lbl_PrecioTotal.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_PrecioTotal.setForeground(new java.awt.Color(0, 102, 102));
        lbl_PrecioTotal.setText("Precio Total");
        getContentPane().add(lbl_PrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 596, -1, -1));
        getContentPane().add(tfd_precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 601, 255, -1));

        lbl_Fotografia.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbl_Fotografia.setForeground(new java.awt.Color(0, 102, 102));
        lbl_Fotografia.setText("Fotografia");
        getContentPane().add(lbl_Fotografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 661, -1, -1));

        lbl_FOTO.setText("jLabel13");
        getContentPane().add(lbl_FOTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 760, 173, 100));

        btn_BuscarFoto.setBackground(new java.awt.Color(153, 153, 153));
        btn_BuscarFoto.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btn_BuscarFoto.setForeground(new java.awt.Color(0, 102, 102));
        btn_BuscarFoto.setText("Buscar Fotografia");
        getContentPane().add(btn_BuscarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 661, -1, -1));
        getContentPane().add(tfd_URLFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 723, 362, 31));

        btn_InsertOProducto.setBackground(new java.awt.Color(153, 153, 153));
        btn_InsertOProducto.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btn_InsertOProducto.setForeground(new java.awt.Color(0, 102, 102));
        btn_InsertOProducto.setText("Insertar");
        getContentPane().add(btn_InsertOProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 904, 276, 63));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertProductoMayorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertProductoMayorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertProductoMayorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertProductoMayorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertProductoMayorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarFoto;
    private javax.swing.JButton btn_InsertOProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Descripcion;
    private javax.swing.JLabel lbl_FOTO;
    private javax.swing.JLabel lbl_Fotografia;
    private javax.swing.JLabel lbl_ID1;
    private javax.swing.JLabel lbl_ID2;
    private javax.swing.JLabel lbl_IDCategoria;
    private javax.swing.JLabel lbl_IDLote;
    private javax.swing.JLabel lbl_InsertProduct;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_PesoTotal;
    private javax.swing.JLabel lbl_PrecioTotal;
    private javax.swing.JLabel lbl_UnidadMedida;
    private javax.swing.JLabel lbl_ValorUnidad;
    private javax.swing.JTextField tfd_Descripcion;
    private javax.swing.JTextField tfd_IDCategoria;
    private javax.swing.JTextField tfd_IDLote;
    private javax.swing.JTextField tfd_Nombre;
    private javax.swing.JTextField tfd_PesoTotal;
    private javax.swing.JTextField tfd_URLFoto;
    private javax.swing.JTextField tfd_UnidadMedida;
    private javax.swing.JTextField tfd_ValorUnidad;
    private javax.swing.JTextField tfd_precioTotal;
    // End of variables declaration//GEN-END:variables
}
